### PR TITLE
Adding view answer feature

### PR DESCRIPTION
**Pull request by Waelahmed99**

### CODE REVIEW

**Comment by kerolloz** [comment]
@Waelahmed99 
Thank you! :sparkles:

**Comment by kerolloz** [comment]
Hey, @Waelahmed99 
There are a couple of issues. Could you please fix them?  

image
image

**Comment by Waelahmed99** [comment]
> Hey, @Waelahmed99
> There are a couple of issues. Could you please fix them?
> 
> image
> image

The (**) after every 'Answer'?
I believe that there is a separator between each type of questions, question 25 is 1 in my branch
Waelahmed99 04-CS-First-Term
)

**Comment by kerolloz** [comment]
Yes, the `**` after every answer. It was originally intended to make the word "answer" **bold**. 

look at the [deployed GitHub page](https://kerolloz.github.io/04-CS-First-Term/data-mining.html#decision-trees-and-classification-rules-can-be-easy-to-interpret--summaryview-answersummary-heavy_check_mark-)

**Pull request merged**
